### ISSUE TITLE
Disponibilização de alterações realizadas 

### ISSUE THREAD

**Issue by MSSantosBR** [marcelomdevasconcellos/emensageria#1]
Marcelo, segue anexo as alterações que realizei em alguns arquivos fontes.

Essas alterações estão relacionadas especificamente com configurações iniciais do app; e são auto-explicativas.

Recomendo realizar um DIFF e analisar se essas alterações valem a pena serem comitadas no repositório.

[emensageria-config.zip](https://github.com/marcelomdevasconcellos/emensageria/files/6479661/emensageria-config.zip)

**Atualizado em: 18/05/2021**
[Dockers para eMensageria](https://github.com/MSSantosBR/MSSstack-docker-emensageria)

**Comment by marcelomdevasconcellos** [comment]
Alterações merjadas no código! Muito obrigado!
