### ISSUE TITLE
psycopg2

### ISSUE THREAD

**Issue by kildary** [marcelomdevasconcellos/emensageria#10]
Boa tarde!
não consigo instalar esse pacote. 
qual a versão do linux é como pre-requisito? instalei o debian11.

**Comment by kildary** [comment]
> 
> 
> Boa tarde! não consigo instalar esse pacote. qual a versão do linux é como pre-requisito? instalei o debian11.

deu certo.
 o erro é esse agora
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'

porém ao pesquisar esse metodos parecem que não existem mais.

**Comment by marcelomdevasconcellos** [comment]
Você instalou o pacote pelo requirements.txt (https://github.com/marcelomdevasconcellos/emensageria/blob/main/requirements.txt) ?

Qual ação que você executou para aparecer este erro ? Me descreve um pouco mais o erro...

**Comment by kildary** [comment]
Deu certo marcelo, 
problema foi que estava com o python 3.9 .
