### ISSUE TITLE
Erro: Verificação CSRF falhou. Pedido cancelado.

### ISSUE THREAD

**Issue by kildary** [marcelomdevasconcellos/emensageria#11]
Estou tentando logar no /api-token-auth/
porém sempre retorna este erro.
já tratou alguma vez?
Tou tentando logar para jogar os dados de um sistema em .net

**Comment by marcelomdevasconcellos** [comment]
Você testou pelo PostMan? viu a collection que eu compartilhei no repositório? 
https://github.com/marcelomdevasconcellos/emensageria/tree/main/docs

**Comment by kildary** [comment]
Aliás. deu certo aqui agora. obrigado
