### ISSUE TITLE
Formato JSon para evento 2400

### ISSUE THREAD

**Issue by Felip3Paz** [marcelomdevasconcellos/emensageria#15]
Olá Marcelo, tudo bem?

Estou com dificuldades para identificar qual o formato do jSon que o eMensageria recebe no evento 2400, por gentileza, teria como ajudar com alguma documentação ou exemplo que contemple esse evento?

Grato desde já!

**Comment by marcelomdevasconcellos** [comment]
Olá! Tudo bem. Para identificação do formato do JSON você poderá acessar o FrontEnd utilizando o usuário admin e criar um evento no leiaute que desejar, após salvar, abra-o para a edição. O formato do JSON irá aparecer em um campo somente leitura no formulario chamado JSON. Sei que talvez não seja a forma mais documentada, mas é a mais segura pois é exatamente como o sistema está criando o JSON.

Para facilitar, estou te enviando o JSON do S-2400 abaixo: {"evtCdBenefIn":{"ideEvento":{"indRetif":"","nrRecibo":"","tpAmb":"2","procEmi":"1","verProc":"1.2.0"},"ideEmpregador":{"tpInsc":"1","nrInsc":"12345678901234"},"beneficiario":{"cpfBenef":"","nmBenefic":"","dtNascto":"","dtInicio":"","sexo":"","racaCor":"","estCiv":"","incFisMen":"","dtIncFisMen":"","endereco":{"brasil":{"tpLograd":"","dscLograd":"","nrLograd":"","complemento":"","bairro":"","cep":"","codMunic":"","uf":""},"exterior":{"paisResid":"","dscLograd":"","nrLograd":"","complemento":"","bairro":"","nmCid":"","codPostal":""}},"dependente":[{"tpDep":"","nmDep":"","dtNascto":"","cpfDep":"","sexoDep":"","depIRRF":"","incFisMen":""}]}}}
