### ISSUE TITLE
Exemplo de campos para envio do 2230

### ISSUE THREAD

**Issue by kildary** [marcelomdevasconcellos/emensageria#16]
bom dia!
vc tem algum exemplo de json para post do 2230?

**Comment by marcelomdevasconcellos** [comment]
Para identificação do formato do JSON para importação siga os seguintes passos:

1. Acessar o FrontEnd utilizando o usuário admin;
2. Criar um evento no leiaute que desejar e salvar o evento;
3. Visualizar a edição do evento;
4. O formato do JSON irá aparecer em um campo somente leitura no formulario chamado JSON.
