### ISSUE TITLE
Eventos Enviados - aguardando consulta

### ISSUE THREAD

**Issue by kildary** [marcelomdevasconcellos/emensageria#19]
Boa tarde! quando enviamos o 2200, 90 deles ficaram como aguardando consulta , porém eles possuem recibo. tem idéia do que poderia ser?

**Comment by marcelomdevasconcellos** [comment]
Não sei dizer, pode ser algum problema no processamento. O recibo está todo preenchido? o Hash está preenchido? 

Somente por curiosidade, se for possível, quantos foram enviados e quantos deram erro? Deu este erro em todos?

Voce pode executar novamente a consulta para ver se identifica o erro. A consulta pode ser executada quantas vezes você quiser, sem problemas.

**Comment by marcelomdevasconcellos** [comment]
Outra coisa. O sistema salva os arquivos XML da consulta, dá uma conferida neles. Se realmente ele foi recebido corretamente.

**Comment by kildary** [comment]
Mais de 1400 enviados e 90 ficaram presos como enviados(aguardando consulta) ao tentar consultar informa o erro: O transmissor ainda não possui um número de protocolo! o XML mostra o hash do  SignatureValue.

**Comment by marcelomdevasconcellos** [comment]
Pode ter dado alguma falha na hora do envio e do processamento do envio... Faz um teste com um deles... importa novamente e tenta enviar... se der certo, apaga estas 90 linhas, importa novamente e faz o envio... (É uma sugestão)
