### ISSUE TITLE
Dificuldade em implantação

### ISSUE THREAD

**Issue by xisberto** [marcelomdevasconcellos/emensageria#2]
Além deste repositório, existem outros 3 com nome parecido, tocados pelas mesmas pessoas:

- https://github.com/leoleotorres/emensageria
- https://github.com/ananiasfilho/emensageriapro
- https://github.com/marcelomdevasconcellos/emensageria

Este repositório está utilizando bibliotecas muito antigas, o que dificulta a implantação. Outros projetos, como https://github.com/marcelomdevasconcellos/emensageria, apresentam uso de bibliotecas mais atuais, mas tem a implantação dificultada por falta de instruções sobre a operação de criação inicial do banco e de migrate.

Assim, resta a dúvida de qual repositório deve ser utilizado, e qual é o procedimento correto de instalação.

**Comment by marcelomdevasconcellos** [comment]
Alguns forks são feitos pelos usuários do github, neste caso não tenho muito controle.

Eu tenho dois depositórios:
- https://github.com/eMensageriaPro/emensageriapro (versão antiga, está depreciado, vou desativar ele);
- https://github.com/marcelomdevasconcellos/emensageria (versão atual que está sendo trabalhada);

Para verificar a versão atual, pode pegar pelo site www.emensageria.com.br, mas pretendo continuar o desenvolvimento neste github (https://github.com/marcelomdevasconcellos/emensageria);

Sobre a instalação, infelizmente não consegui preparar ainda a documentação de instalação, mas a instalação é básica do django, vou te orientar para criação de um ambiente de desenvolvimento:


Criação de banco de dados em postgres:
  host: localhost
  name: emensageria
  user: postgres
  pass: postgres
  port: 5432

$ python3 -m venv venv_emensageria (Criação de virtualenv)
$ pip install -r requirements.txt (Instalação de requirements)
$ source venv_emensageria/bin/activate (Ativação da virtualenv)
$ cp .env_example .env (Inserir configurações) 
$ python manage.py migrate (Criação do banco de dados)
$ python manage.py createsuperuser (Criação do super usuário)

O resto é configurações pelo sistema, na sequencia:
1) Certificado
2) Transmissor
3) Eventos ...

**Comment by xisberto** [comment]
Obrigado pelo esclarescimento. Conseguimos realizar a implantação.
