### ISSUE TITLE
Evento 2420

### ISSUE THREAD

**Issue by kildary** [marcelomdevasconcellos/emensageria#20]
Bom dia!
O evento 2420 está implementado?

Ao criar é devolvido o erro abaixo:
TemplateDoesNotExist at /esocial/eventos/39317/change/
v_S_01_00_00/s2428.html

**Comment by marcelomdevasconcellos** [comment]
Identifiquei o problema e já enviei a correção. Recomendo atualizar o sistema completo, mas caso não queira pode fazer somente a correção, segue o link para identificar o que foi alterado: https://github.com/marcelomdevasconcellos/emensageria/commit/8e3e17207895cf4e361a0e586a9f4f209ec7e9dd

Muito obrigado! Por favor, me retorne caso ainda persista o erro.
