### ISSUE TITLE
Problema em mostrar dados no evento s1200

### ISSUE THREAD

**Issue by lucasmrmc17** [marcelomdevasconcellos/emensageria#29]
Ola Marcelo, bom dia, quando fazemos a inclusão de um novo evento s1200 pelo portal do emensageria, incluimos todos os dados necessários, incluido o nome do empregador, data de nascimento e os codigos de rubricas, no entando, quando savamos o evento ele não mostra mais as rubricas cadastradas. O mesmo acontece quando enviamos os dados via API.

<img width="848" alt="Screenshot_5" src="https://user-images.githubusercontent.com/36051351/183082679-f371d86b-44f6-4820-a4ea-92f5fabbc140.png">

<img width="846" alt="Screenshot_6" src="https://user-images.githubusercontent.com/36051351/183082718-c3a1a8d6-2fdc-4ba5-9bd3-14de3bc915cd.png">

Poderia nos ajudar a respeito disso.

**Comment by marcelomdevasconcellos** [comment]
Olá Lucas, Enviei um push agora. Por gentileza verifica se o erro foi resolvido, se não me retorna. Obrigado!

**Comment by lucasmrmc17** [comment]
Marcelo, bom dia.
Fiz uns testes aqui e deu tudo certo. Muito obrigado pela sua atenção e prontidão.

Att,
Lucas Mota
