### ISSUE TITLE
Problema em mostrar dados no evento s2298

### ISSUE THREAD

**Issue by lucasmrmc17** [marcelomdevasconcellos/emensageria#31]
Marcelo, boa tarde, seguimos com alguns testes enviados para o emensageria e o seguinte problema.
Ao enviarmos os dados via api observamos que todos os dados são passados corretamente pela api, como visto na imagem 1, mas quando abrimos o evento no emenssageria os dados ficam inconsistentes com o que foi passado, imagem 2.

![WhatsApp Image 2022-08-08 at 15 10 42](https://user-images.githubusercontent.com/36051351/183485178-00522082-5e31-47e4-b504-8c9a33805a11.jpeg)
**Imagem 1**

<img width="740" alt="Screenshot_1" src="https://user-images.githubusercontent.com/36051351/183485274-ae453fff-a917-4e4f-a9ce-9e58c83805e6.png">
Imagem 2

Grato pela atenção
Lucas M

**Comment by marcelomdevasconcellos** [comment]
Olá Lucas, 

Aparentemente está sendo enviado um campo datetime, vou te pedir para fazer um teste enviando um campo apenas de data, no formado AAAA-MM-DD . 

Você pode fazer este teste e me repassar o resultado?

Caso persista o erro, vou te pedir mais detalhes de como está sendo passado por meio da API para que eu possa realizar testes.

**Comment by lucasmrmc17** [comment]
Marcelo, era esse mesmo o problema, eu estava passando um datetime, ao passar no formato indicado por você deu certo. Obrigado pela atenção.
