### ISSUE TITLE
Formato do Certificado do Cliente

### ISSUE THREAD

**Issue by xisberto** [marcelomdevasconcellos/emensageria#4]
Ao tentar enviar um evento, é exibida a mensagem:

> Não foi recebida nenhuma resposta do servidor. Verifique se a pasta /arquivos/ está com permissão de escrita ou pode ter ocorrido erro de timeout. Timeout atual 3600

No log, é exibida a mensagem:

`curl: (58) could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?)`

Desconfio que a falha ao tentar abrir o certificado esteja causando o erro no envio, já que não é problema de permissão.

O certificado do cliente foi adicionado como PFX, mas a mensagem de log informa PEM. Há alguma exigência no tipo de certificado que deve ser usado? Qual conteúdo e formato deve ter o certificado? É obrigatório que ele tenha uma senha?

**Comment by marcelomdevasconcellos** [comment]
Fiz uma correção das pastas a pouco tempo. 
Tem que inserir uma variável CERT_PATH no .env... (Veja o exemplo: https://github.com/marcelomdevasconcellos/emensageria/blob/main/config/.env_example)

Você cadastra o PFX e ele cria os arquivos PEM (cert.pem e key.pem)... Tem que verificar esta pasta para saber se ela tem a permissão de escrita e se o sistema está escrevendo na pasta correta.

**Comment by xisberto** [comment]
Foi feita a configuração do CERT_PATH e depois cadastrado o mesmo arquivo PFX como um novo certificado.

Foi verificado que os arquivos PEM foram criados.

Mas durante as operações descritas na issue #5 o django.log apresenta o mesmo erro acima.

**Comment by marcelomdevasconcellos** [comment]
Ele salva o comando utilizado para envio na pasta "arquivos/comunicacao/WsEnviarLoteEventos/command" .. Copia aqui o ultimo comando salvo nesta pasta.

**Comment by marcelomdevasconcellos** [comment]
Desculpa.. aparentemente ele leu os certificados corretamente.. agora o erro foi na geração do XML!

**Comment by marcelomdevasconcellos** [comment]
Vou finalizar esta issue, pois acredito que o problema foi corrigido. Caso haja necessidade favor abrir outra.
