### ISSUE TITLE
Auxilio para resolver erro de envio aguardando correção no S-1020 Tabela de Lotações Tributárias

### ISSUE THREAD

**Issue by ricardodepaula** [marcelomdevasconcellos/emensageria#5]
Bom dia,

Cadastramos um usuário e um registro do evento S-1020 - Tabela de Lotações Tributárias está na caixa erros de envio aguardando correção do Dashboard.

Quando eu clico em visualizar e em corrigir são apresentados os erros abaixo:

Tipo: ERRO
Descrição: Unexpected child with tag 'tpInsc' at position 1. Tag 'tpLotacao' expected.
Localização: /eSocial/evtTabLotacao/infoLotacao/alteracao/dadosLotacao

Tipo: ERRO
Descrição: Unexpected child with tag 'dadosLotacao' at position 1. Tag 'ideLotacao' expected.
Localização: /eSocial/evtTabLotacao/infoLotacao/alteracao

Tipo: ERRO
Descrição: Unexpected child with tag 'alteracao' at position 2. No child element is expected at this point.
Localização: /eSocial/evtTabLotacao/infoLotacao

O Evento S-1000 ainda não foi enviado e estamos tratando erro de envio com a ajuda do xisberto e sua nas respostas aos questionamentos dele.

Pensei em remover o registro S-1020 na tela de evetos utilizando o combo remover eventos selecionados e clicando no botão ir, ele vai para a tela Remover múltiplos objetos, porem é exibida a informação que a minha conta não tem permissão para excluir os seguintes tipos de objetos: 1 Evento, sendo que adicionei todas as permissões ao meu usuário, com o usuário administrador também não foi possível.

Gostaria de saber como devo proceder em relação as mensagens acima.

**Comment by marcelomdevasconcellos** [comment]
Foi corrigida a funcionalidade de apagar eventos neste final de semana, por favor, atualize o repositorio. Já os erros reportados acima vou ver se identifico algo, mas depende o XML, precisa verificar como o XML está sendo criado. Caso eu encontre algo reportarei aqui.

**Comment by ricardodepaula** [comment]
Aparentemente ele está criando o xml com as tags: 

<inclusao>
<alteracao>
e <exclusao>

no mesmo XML

Deveria ser apenas a tag inclusao já que estou cadastrando como inclusão correto?

**Comment by ricardodepaula** [comment]
Aparentemente ele está criando o xml com as tags:

inclusao
alteracao
e exclusao

no mesmo XML

Deveria ser apenas a tag inclusao já que estou cadastrando como inclusão correto?

**Comment by ricardodepaula** [comment]
Aparentemente ele está criando o xml com as tags: inclusao e alteracao no mesmo XML.

Deveria ser apenas a tag inclusao já que estou cadastrando como inclusão correto?

O S-1005 apresenta o mesmo problema, ele está gerando as tags de inclusão, alteração e exclusão no mesmo XML.

**Comment by marcelomdevasconcellos** [comment]
Vou verificar este BUG mais tarde e envio a correção ainda hoje.

**Comment by marcelomdevasconcellos** [comment]
Fiz um PULL agora a pouco. Favor conferir e reportar caso o problema persista.

**Comment by ricardodepaula** [comment]
Obrigado Marcelo, problema resolvido.
