### ISSUE TITLE
erro de envio Aguardando correção no evento S-1005

### ISSUE THREAD

**Issue by ricardodepaula** [marcelomdevasconcellos/emensageria#6]
Boa Tarde,

Ao tentar enviar o evento S-1005 para o ambiente restrito o e-Social retornou as ocorrências abaixo:

Ocorrência(s)!

Tipo: ERRO
Descrição: 852 - A informação contida no campo FAP deve possuir o mesmo valor em todo o período do evento, em relação à origem do seu cadastro (eventos do empregador, tabelas, sistemas externos, tabelas de referências, etc). Ação sugerida: Corrigir o valor do campo ou o período da informação no evento, ou providenciar o acerto da informação contida no campo no seu cadastro de origem.
Localização: /eSocial/evtTabEstab/infoEstab/inclusao/dadosEstab/aliqGilrat/fap

Tipo: ERRO
Descrição: 1513 - Valor do FAP inválido. Ação Sugerida: Verifique se o valor preenchido está entre 0,5000 e 2,0000 e se o estabelecimento for CNPJ, este valor deve ser diferente do valor definido pelo órgão governamental competente.
Localização: /eSocial/evtTabEstab/infoEstab/inclusao/dadosEstab/aliqGilrat/fap

Tipo: ERRO
Descrição: 1508 - Deve existir informação sobre o processo administrativo/judicial que permite o preenchimento de fator diferente. Ação Sugerida: Deverá haver informações de processo em procAdmJudFap.
Localização: /eSocial/evtTabEstab/infoEstab/inclusao/dadosEstab/aliqGilrat/fap

No XML o trecho da alíquota está utilizando o ponto (.) 0.50 como separador decimal, o correto não seria a virgula (,) 0,50?

<aliqGilrat>
<fap>0.50</fap>
</aliqGilrat>

OBS: O Sistema não permite que seja informada a virgula (,) ele mesmo já preenche com o ponto (.)

**Comment by ricardodepaula** [comment]
aliqGilrat
   fap 0.50 /fap
/aliqGilrat

**Comment by marcelomdevasconcellos** [comment]
Pelo que observei no XSD o separador decimal é o ponto ".", uma prova é que ele passou pela validação do XSD e barrou na validação do eSocial, vamos precisar identificar melhor os erros.

```<!-- Campo {fap} -->
<xs:simpleType name="TS_fap">
    <xs:restriction base="xs:decimal">
        <xs:totalDigits value="5" />
        <xs:fractionDigits value="4" />
        <xs:minInclusive value="0.5" />
        <xs:maxInclusive value="2" />
    </xs:restriction>
</xs:simpleType>```

Pode me passar o trecho do XML?

**Comment by ricardodepaula** [comment]
`   <evtTabEstab Id="IDXXXXXXXXXXXXXXXXXXX">
      <ideEvento>
         <tpAmb>2</tpAmb>
         <procEmi>1</procEmi>
         <verProc>1.0.0</verProc>
      </ideEvento>
      <ideEmpregador>
         <tpInsc>1</tpInsc>
         <nrInsc>XXXXXXXX</nrInsc>
      </ideEmpregador>
      <infoEstab>
         <inclusao>
            <ideEstab>
               <tpInsc>1</tpInsc>
               <nrInsc>XXXXXXXXXXXXXX</nrInsc>
               <iniValid>2021-06</iniValid>
            </ideEstab>
            <dadosEstab>
               <cnaePrep>8411600</cnaePrep>
               <aliqGilrat>
                  <fap>0.50</fap>
               </aliqGilrat>
            </dadosEstab>
         </inclusao>
      </infoEstab>
   </evtTabEstab>`

**Comment by ricardodepaula** [comment]
Marcelo deu certo, não deveríamos ter informado o fap, apenas se ele fosse diferente do padrão, Obrigado.
