### ISSUE TITLE
Configuração do ambiente de Produção

### ISSUE THREAD

**Issue by ricardodepaula** [marcelomdevasconcellos/emensageria#7]
Bom dia,

Marcelo, setei o campo ESOCIAL_TP_AMB na tela de configurações para Produção porem ao tentar cadastrar um evento a combo Identificação do ambiente vem preenchida com o registro 2 - Produção restrita na tela de cadastro de eventos e essa combo é somente leitura.

Você tem ideia do que pode estar acontecendo e pode nos ajudar por gentileza?

**Comment by marcelomdevasconcellos** [comment]
Bom dia!

Por gentileza faça a atualização do código, pois eu descomentei o caminho do serviço de produção.
Para uma configuração mais seguro o TPAMB está configurando no arquivo ".env", neste caso é necessário alterar a variável ESOCIAL_TPAMB no ".env".

Veja em: https://github.com/marcelomdevasconcellos/emensageria/blob/main/config/.env_example
