### ISSUE TITLE
Dúvida XML

### ISSUE THREAD

**Issue by kildary** [marcelomdevasconcellos/emensageria#9]
O emensageria consegue ler um xml? desculpe a pergunta tou tentando entender como funciona.
consigo pelo meu sistema montar um xml e jogar pra ele?

**Comment by marcelomdevasconcellos** [comment]
Sim! Algumas empresas estão trabalhando importando o XML. Só precisa ver uns detalhes de como seu sistema está gerando o XML e você fazer uns testes. Tem uma collection do PostMan no repositório com exemplos da api de importação com XML.

**Comment by marcelomdevasconcellos** [comment]
https://github.com/marcelomdevasconcellos/emensageria/tree/main/docs
